version: '3.2'

services:

    es0:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
        container_name: es0
        environment:
            discovery.type: single-node
        ports:
            - 9200:9200
            - 9300:9300
        networks:
            esnet:
                aliases:
                    - elasticsearch

    kibana:
        image: docker.elastic.co/kibana/kibana:7.2.0
        container_name: kibana
        ports:
            - 5601:5601
        networks:
            esnet:
        depends_on:
            - es0

    filebeat:
        image: docker.elastic.co/beats/filebeat:7.2.0
        container_name: filebeat
        volumes:
            - type: bind
              source: ./data/
              target: /usr/share/filebeat/data/
            - type: bind
              source: ./filebeat.yml
              target: /usr/share/filebeat/filebeat.yml
        networks:
            esnet:
        depends_on:
            - es0

    logstash:
        image: docker.elastic.co/logstash/logstash:7.2.0
        container_name: logstash
        environment:
            xpack.monitoring.enabled: "true"
        volumes:
            - type: bind
              source: ./pipeline/
              target: /usr/share/logstash/pipeline/
        networks:
            esnet:
        depends_on:
            - es0
        

networks:
    esnet:
